package Modelo;
// Generated 3/04/2016 11:49:30 PM by Hibernate Tools 4.3.1



/**
 * Consumidor generated by hbm2java
 */
public class Consumidor  implements java.io.Serializable {


     private String usuario;
     private String nombre;
     private String apellidos;
     private String correo;
     private Integer calificacion;

    public Consumidor() {
    }

	
    public Consumidor(String usuario) {
        this.usuario = usuario;
    }
    public Consumidor(String usuario, String nombre, String apellidos, String correo, Integer calificacion) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.correo = correo;
       this.calificacion = calificacion;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }




}


